'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserName() As String
            Get
                Return CType(Me("UserName"),String)
            End Get
            Set
                Me("UserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ClockColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ClockColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ClockColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Teal")>  _
        Public Property WorkColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("WorkColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("WorkColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DesktopColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("DesktopColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("DesktopColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserPass() As String
            Get
                Return CType(Me("UserPass"),String)
            End Get
            Set
                Me("UserPass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserHint() As String
            Get
                Return CType(Me("UserHint"),String)
            End Get
            Set
                Me("UserHint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property WBarColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("WBarColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("WBarColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowDesktop() As Boolean
            Get
                Return CType(Me("ShowDesktop"),Boolean)
            End Get
            Set
                Me("ShowDesktop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowClock() As Boolean
            Get
                Return CType(Me("ShowClock"),Boolean)
            End Get
            Set
                Me("ShowClock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AreLogin() As Boolean
            Get
                Return CType(Me("AreLogin"),Boolean)
            End Get
            Set
                Me("AreLogin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property StatusBar() As Boolean
            Get
                Return CType(Me("StatusBar"),Boolean)
            End Get
            Set
                Me("StatusBar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CalendarWallpaper() As String
            Get
                Return CType(Me("CalendarWallpaper"),String)
            End Get
            Set
                Me("CalendarWallpaper") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WelcomeText() As Boolean
            Get
                Return CType(Me("WelcomeText"),Boolean)
            End Get
            Set
                Me("WelcomeText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BGimage() As String
            Get
                Return CType(Me("BGimage"),String)
            End Get
            Set
                Me("BGimage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0.1.6")>  _
        Public Property Version() As String
            Get
                Return CType(Me("Version"),String)
            End Get
            Set
                Me("Version") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property IsAdmin() As Boolean
            Get
                Return CType(Me("IsAdmin"),Boolean)
            End Get
            Set
                Me("IsAdmin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property D() As String
            Get
                Return CType(Me("D"),String)
            End Get
            Set
                Me("D") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Google")>  _
        Public Property SearchEngine() As String
            Get
                Return CType(Me("SearchEngine"),String)
            End Get
            Set
                Me("SearchEngine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property GlobalSecurityUse() As Boolean
            Get
                Return CType(Me("GlobalSecurityUse"),Boolean)
            End Get
            Set
                Me("GlobalSecurityUse") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property GeographyGame() As Boolean
            Get
                Return CType(Me("GeographyGame"),Boolean)
            End Get
            Set
                Me("GeographyGame") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Stretch")>  _
        Public Property WallpaperType() As String
            Get
                Return CType(Me("WallpaperType"),String)
            End Get
            Set
                Me("WallpaperType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property geographygametotalopened() As String
            Get
                Return CType(Me("geographygametotalopened"),String)
            End Get
            Set
                Me("geographygametotalopened") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Standard")>  _
        Public Property CalendarType() As String
            Get
                Return CType(Me("CalendarType"),String)
            End Get
            Set
                Me("CalendarType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property JokeWeb() As Boolean
            Get
                Return CType(Me("JokeWeb"),Boolean)
            End Get
            Set
                Me("JokeWeb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property jokewebtotalopened() As String
            Get
                Return CType(Me("jokewebtotalopened"),String)
            End Get
            Set
                Me("jokewebtotalopened") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PaintMax() As Boolean
            Get
                Return CType(Me("PaintMax"),Boolean)
            End Get
            Set
                Me("PaintMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property paintmaxtotalopened() As String
            Get
                Return CType(Me("paintmaxtotalopened"),String)
            End Get
            Set
                Me("paintmaxtotalopened") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property snakegametotalopened() As String
            Get
                Return CType(Me("snakegametotalopened"),String)
            End Get
            Set
                Me("snakegametotalopened") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SnakeGame() As Boolean
            Get
                Return CType(Me("SnakeGame"),Boolean)
            End Get
            Set
                Me("SnakeGame") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SnakeGameBestScore() As String
            Get
                Return CType(Me("SnakeGameBestScore"),String)
            End Get
            Set
                Me("SnakeGameBestScore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TicTacToeGame() As Boolean
            Get
                Return CType(Me("TicTacToeGame"),Boolean)
            End Get
            Set
                Me("TicTacToeGame") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property tictactoegametotalopened() As String
            Get
                Return CType(Me("tictactoegametotalopened"),String)
            End Get
            Set
                Me("tictactoegametotalopened") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SnakeGameGamesCount() As String
            Get
                Return CType(Me("SnakeGameGamesCount"),String)
            End Get
            Set
                Me("SnakeGameGamesCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TicTacToeGameCount() As String
            Get
                Return CType(Me("TicTacToeGameCount"),String)
            End Get
            Set
                Me("TicTacToeGameCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property pingpongtotalopened() As String
            Get
                Return CType(Me("pingpongtotalopened"),String)
            End Get
            Set
                Me("pingpongtotalopened") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PingPong() As Boolean
            Get
                Return CType(Me("PingPong"),Boolean)
            End Get
            Set
                Me("PingPong") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property PingPongGameCount() As String
            Get
                Return CType(Me("PingPongGameCount"),String)
            End Get
            Set
                Me("PingPongGameCount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ApplicationMenuColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ApplicationMenuColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ApplicationMenuColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.75")>  _
        Public Property EmuVer() As String
            Get
                Return CType(Me("EmuVer"),String)
            End Get
            Set
                Me("EmuVer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property StartupSound() As Boolean
            Get
                Return CType(Me("StartupSound"),Boolean)
            End Get
            Set
                Me("StartupSound") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property idkey() As String
            Get
                Return CType(Me("idkey"),String)
            End Get
            Set
                Me("idkey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property UserPicture() As String
            Get
                Return CType(Me("UserPicture"),String)
            End Get
            Set
                Me("UserPicture") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property FoodExpert() As Boolean
            Get
                Return CType(Me("FoodExpert"),Boolean)
            End Get
            Set
                Me("FoodExpert") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Matrix() As Boolean
            Get
                Return CType(Me("Matrix"),Boolean)
            End Get
            Set
                Me("Matrix") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CustomThemes() As String
            Get
                Return CType(Me("CustomThemes"),String)
            End Get
            Set
                Me("CustomThemes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MusicComposer() As Boolean
            Get
                Return CType(Me("MusicComposer"),Boolean)
            End Get
            Set
                Me("MusicComposer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SuperText() As Boolean
            Get
                Return CType(Me("SuperText"),Boolean)
            End Get
            Set
                Me("SuperText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property supertexttotalopened() As String
            Get
                Return CType(Me("supertexttotalopened"),String)
            End Get
            Set
                Me("supertexttotalopened") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ClockType() As String
            Get
                Return CType(Me("ClockType"),String)
            End Get
            Set
                Me("ClockType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AFRandomFact() As Boolean
            Get
                Return CType(Me("AFRandomFact"),Boolean)
            End Get
            Set
                Me("AFRandomFact") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("250")>  _
        Public Property AFRandomFactSpeed() As String
            Get
                Return CType(Me("AFRandomFactSpeed"),String)
            End Get
            Set
                Me("AFRandomFactSpeed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AFRoundedIcons() As Boolean
            Get
                Return CType(Me("AFRoundedIcons"),Boolean)
            End Get
            Set
                Me("AFRoundedIcons") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property InstalledApplications() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("InstalledApplications"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("InstalledApplications") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property InstalledApplicationNames() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("InstalledApplicationNames"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("InstalledApplicationNames") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property InstalledApplicationIconDir() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("InstalledApplicationIconDir"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("InstalledApplicationIconDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property InstalledApplicationClassSettings() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("InstalledApplicationClassSettings"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("InstalledApplicationClassSettings") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property OSLaunched() As String
            Get
                Return CType(Me("OSLaunched"),String)
            End Get
            Set
                Me("OSLaunched") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property InstalledApplicationColor() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("InstalledApplicationColor"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("InstalledApplicationColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ShutdownLog() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ShutdownLog"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("ShutdownLog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property LogInLog() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("LogInLog"),Global.System.Collections.Specialized.StringCollection)
            End Get
            Set
                Me("LogInLog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Use24ClockFormat() As Boolean
            Get
                Return CType(Me("Use24ClockFormat"),Boolean)
            End Get
            Set
                Me("Use24ClockFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property DateFormat() As String
            Get
                Return CType(Me("DateFormat"),String)
            End Get
            Set
                Me("DateFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property FailedLoginAttempts() As Integer
            Get
                Return CType(Me("FailedLoginAttempts"),Integer)
            End Get
            Set
                Me("FailedLoginAttempts") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property AccountLockedUntil() As Date
            Get
                Return CType(Me("AccountLockedUntil"),Date)
            End Get
            Set
                Me("AccountLockedUntil") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TaskbarShow() As Boolean
            Get
                Return CType(Me("TaskbarShow"),Boolean)
            End Get
            Set
                Me("TaskbarShow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TaskbarOrder() As String
            Get
                Return CType(Me("TaskbarOrder"),String)
            End Get
            Set
                Me("TaskbarOrder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CPUName() As String
            Get
                Return CType(Me("CPUName"),String)
            End Get
            Set
                Me("CPUName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property GPUName() As String
            Get
                Return CType(Me("GPUName"),String)
            End Get
            Set
                Me("GPUName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CalendarTransparentBG() As Boolean
            Get
                Return CType(Me("CalendarTransparentBG"),Boolean)
            End Get
            Set
                Me("CalendarTransparentBG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CalendarReminders() As String
            Get
                Return CType(Me("CalendarReminders"),String)
            End Get
            Set
                Me("CalendarReminders") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.PCBaOS.My.MySettings
            Get
                Return Global.PCBaOS.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
